// Generated by gencpp from file analytic_solver/analyticRequest.msg
// DO NOT EDIT!


#ifndef ANALYTIC_SOLVER_MESSAGE_ANALYTICREQUEST_H
#define ANALYTIC_SOLVER_MESSAGE_ANALYTICREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace analytic_solver
{
template <class ContainerAllocator>
struct analyticRequest_
{
  typedef analyticRequest_<ContainerAllocator> Type;

  analyticRequest_()
    : a(0)
    , b(0)  {
    }
  analyticRequest_(const ContainerAllocator& _alloc)
    : a(0)
    , b(0)  {
  (void)_alloc;
    }



   typedef int64_t _a_type;
  _a_type a;

   typedef int64_t _b_type;
  _b_type b;





  typedef boost::shared_ptr< ::analytic_solver::analyticRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::analytic_solver::analyticRequest_<ContainerAllocator> const> ConstPtr;

}; // struct analyticRequest_

typedef ::analytic_solver::analyticRequest_<std::allocator<void> > analyticRequest;

typedef boost::shared_ptr< ::analytic_solver::analyticRequest > analyticRequestPtr;
typedef boost::shared_ptr< ::analytic_solver::analyticRequest const> analyticRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::analytic_solver::analyticRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::analytic_solver::analyticRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::analytic_solver::analyticRequest_<ContainerAllocator1> & lhs, const ::analytic_solver::analyticRequest_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a &&
    lhs.b == rhs.b;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::analytic_solver::analyticRequest_<ContainerAllocator1> & lhs, const ::analytic_solver::analyticRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace analytic_solver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::analytic_solver::analyticRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::analytic_solver::analyticRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::analytic_solver::analyticRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::analytic_solver::analyticRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::analytic_solver::analyticRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::analytic_solver::analyticRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::analytic_solver::analyticRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "36d09b846be0b371c5f190354dd3153e";
  }

  static const char* value(const ::analytic_solver::analyticRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x36d09b846be0b371ULL;
  static const uint64_t static_value2 = 0xc5f190354dd3153eULL;
};

template<class ContainerAllocator>
struct DataType< ::analytic_solver::analyticRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "analytic_solver/analyticRequest";
  }

  static const char* value(const ::analytic_solver::analyticRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::analytic_solver::analyticRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 a\n"
"int64 b\n"
;
  }

  static const char* value(const ::analytic_solver::analyticRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::analytic_solver::analyticRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct analyticRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::analytic_solver::analyticRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::analytic_solver::analyticRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<int64_t>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<int64_t>::stream(s, indent + "  ", v.b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ANALYTIC_SOLVER_MESSAGE_ANALYTICREQUEST_H
