// Generated by gencpp from file analytic_solver/analyticResponse.msg
// DO NOT EDIT!


#ifndef ANALYTIC_SOLVER_MESSAGE_ANALYTICRESPONSE_H
#define ANALYTIC_SOLVER_MESSAGE_ANALYTICRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace analytic_solver
{
template <class ContainerAllocator>
struct analyticResponse_
{
  typedef analyticResponse_<ContainerAllocator> Type;

  analyticResponse_()
    : sum(0)  {
    }
  analyticResponse_(const ContainerAllocator& _alloc)
    : sum(0)  {
  (void)_alloc;
    }



   typedef int64_t _sum_type;
  _sum_type sum;





  typedef boost::shared_ptr< ::analytic_solver::analyticResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::analytic_solver::analyticResponse_<ContainerAllocator> const> ConstPtr;

}; // struct analyticResponse_

typedef ::analytic_solver::analyticResponse_<std::allocator<void> > analyticResponse;

typedef boost::shared_ptr< ::analytic_solver::analyticResponse > analyticResponsePtr;
typedef boost::shared_ptr< ::analytic_solver::analyticResponse const> analyticResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::analytic_solver::analyticResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::analytic_solver::analyticResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::analytic_solver::analyticResponse_<ContainerAllocator1> & lhs, const ::analytic_solver::analyticResponse_<ContainerAllocator2> & rhs)
{
  return lhs.sum == rhs.sum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::analytic_solver::analyticResponse_<ContainerAllocator1> & lhs, const ::analytic_solver::analyticResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace analytic_solver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::analytic_solver::analyticResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::analytic_solver::analyticResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::analytic_solver::analyticResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::analytic_solver::analyticResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::analytic_solver::analyticResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::analytic_solver::analyticResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::analytic_solver::analyticResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b88405221c77b1878a3cbbfff53428d7";
  }

  static const char* value(const ::analytic_solver::analyticResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb88405221c77b187ULL;
  static const uint64_t static_value2 = 0x8a3cbbfff53428d7ULL;
};

template<class ContainerAllocator>
struct DataType< ::analytic_solver::analyticResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "analytic_solver/analyticResponse";
  }

  static const char* value(const ::analytic_solver::analyticResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::analytic_solver::analyticResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 sum\n"
"\n"
;
  }

  static const char* value(const ::analytic_solver::analyticResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::analytic_solver::analyticResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct analyticResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::analytic_solver::analyticResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::analytic_solver::analyticResponse_<ContainerAllocator>& v)
  {
    s << indent << "sum: ";
    Printer<int64_t>::stream(s, indent + "  ", v.sum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ANALYTIC_SOLVER_MESSAGE_ANALYTICRESPONSE_H
